module.exports = {
  hubilo: [
    { alias: 'event-masters', name: 'Event Masters' },
    { alias: 'white-papers', name: 'Whitepapers & E-Books' },
    { alias: 'webinars', name: 'Webinars' },
    { alias: 'thought-leadership', name: 'Thought Leadership' },
    { alias: 'podcasts', name: 'Podcasts' },
    { adId: 'gpt-ad-rail1' },
  ],
  'bizbash-lists': [
    { alias: 'top-100-events', name: 'Top 100 Events' },
    { alias: 'brands-event-pros', name: 'Brands & Event Pros' },
    { alias: 'meetings-conferences', name: 'Meetings & Conferences' },
  ],
  'catering-design': [
    { alias: 'beverages', name: 'Beverages' },
    { alias: 'food-trends', name: 'Food Trends' },
    { alias: 'event-design-decor', name: 'Event Design & Decor' },
    { alias: 'florals', name: 'Florals' },
    { alias: 'gifts-swag', name: 'Gifts & Swag' },
    { adId: 'gpt-ad-rail1' },
    { alias: 'rentals', name: 'Rentals' },
    { alias: 'tabletop', name: 'Tabletop' },
    { alias: 'printing-graphics', name: 'Printing & Graphics' },
  ],
  'event-tech-virtual': [
    { alias: 'hybrid-virtual-event-production', name: 'Hybrid & Virtual Event Production' },
    { alias: 'virtual-entertainment-gifts', name: 'Virtual Entertainment & Gifts' },
    { alias: 'event-tech-tools', name: 'Event Tech & Tools' },
    { alias: 'strategy', name: 'Strategy' },
  ],
  'meetings-trade-shows': [
    { alias: 'meetings', name: 'Meetings' },
    { alias: 'strategy', name: 'Strategy' },
    { alias: 'trade-shows', name: 'Trade Shows' },
    { alias: 'people', name: 'People' },
    { alias: 'places', name: 'Places' },
    { alias: 'trends', name: 'Trends' },
  ],
  'on-demand': [
    { alias: 'event-masters', name: 'Event Masters' },
    { alias: 'webinars-virtual-events', name: 'Webinars & Virtual Events' },
    { alias: 'gathergeeks', name: 'GatherGeeks' },
  ],
  'production-strategy': [
    { alias: 'audiovisual-lighting', name: 'Audiovisual & Lighting' },
    { alias: 'experiential-marketing-activations-sponsorships', name: 'Experiential Marketing, Activations & Sponsorships' },
    { alias: 'event-management', name: 'Event Management' },
    { alias: 'event-production-fabrication', name: 'Event Production & Fabrication' },
    { alias: 'opinion-experts', name: 'Opinion & Experts' },
    { alias: 'programming-entertainment', name: 'Programming & Entertainment' },
    { alias: 'registration-ticketing', name: 'Registration & Ticketing' },
    { alias: 'social-events', name: 'Social Events' },
    { alias: 'strategy', name: 'Strategy' },
  ],
};
